from enum import Enum


class Operands(Enum):
    REG = "reg"
    MEM = "mem"
    DATA = "data"


class Registers(Enum):
    AL = "al"
    AH = "ah"
    AX = "ax"
    EAX = "eax"
    RAX = "rax"
    BL = "bl"
    BH = "bh"
    BX = "bx"
    EBX = "ebx"
    RBX = "rbx"
    CL = "cl"
    CH = "ch"
    CX = "cx"
    ECX = "ecx"
    RCX = "rcx"
    DL = "dl"
    DH = "dh"
    DX = "dx"
    EDX = "edx"
    RDX = "rdx"
    CS = "cs"
    DS = "ds"
    SS = "ss"
    ES = "es"
    FS = "fs"
    GS = "gs"
    SPL = "spl"
    SP = "sp"
    ESP = "esp"
    RSP = "rsp"
    BPL = "bpl"
    BP = "bp"
    EBP = "ebp"
    RBP = "rbp"
    SIL = "sil"
    SI = "si"
    ESI = "esi"
    RSI = "rsi"
    DIL = "dil"
    DI = "di"
    EDI = "edi"
    RDI = "rdi"
    IP = "ip"
    EIP = "eip"
    RIP = "rip"
    R8B = "r8b"
    R8W = "r8w"
    R8D = "r8d"
    R8 = "r8"
    R9B = "r9b"
    R9W = "r9w"
    R9D = "r9d"
    R9 = "r9"
    R10B = "r10b"
    R10W = "r10w"
    R10D = "r10d"
    R10 = "r10"
    R11B = "r11b"
    R11W = "r11w"
    R11D = "r11d"
    R11 = "r11"
    R12B = "r12b"
    R12W = "r12w"
    R12D = "r12d"
    R12 = "r12"
    R13B = "r13b"
    R13W = "r13w"
    R13D = "r13d"
    R13 = "r13"
    R14B = "r14b"
    R14W = "r14w"
    R14D = "r14d"
    R14 = "r14"
    R15B = "r15b"
    R15W = "r15w"
    R15D = "r15d"
    R15 = "r15"


class MemoryMode(Enum):
    BYTE = "byte"
    WORD = "word"
    DWORD = "dword"
    QWORD = "qword"

